# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50a69d83ab2362b23a4ecc591ba5b2a2e61398adc4dbf941c16dae61c8b658cdd977f87bc905fe7c762f4c3a74f55c5738f34d9697223afa21b1fb55e4620aea

test:
  secret_key_base: 2b3044102a416a76687069d4d8e99c94c86a9e2de2083f3196331f1b162eb6a5465ef171e869bb24cba24951c268ca70efde18c1fa20cba768f315a226d6d011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
